const { Inventory } = require('../models');

const additionalInventoryData = [
  // Additional Food Supplies
  {
    name: 'Wheat Flour',
    category: 'food_supplies',
    subcategory: 'Grains',
    currentStock: 50,
    minimumStock: 15,
    maximumStock: 100,
    unit: 'kg',
    unitPrice: 45,
    supplier: 'Grain Suppliers',
    supplierContact: '+919876543304',
    location: 'Storage Room',
    description: 'Premium wheat flour for bread and rotis',
    alertEnabled: true
  },
  {
    name: 'Rice Flour',
    category: 'food_supplies',
    subcategory: 'Grains',
    currentStock: 25,
    minimumStock: 8,
    maximumStock: 50,
    unit: 'kg',
    unitPrice: 60,
    supplier: 'Grain Suppliers',
    supplierContact: '+919876543304',
    location: 'Storage Room',
    description: 'Fine rice flour for South Indian dishes',
    alertEnabled: true
  },
  {
    name: 'Chickpea Flour',
    category: 'food_supplies',
    subcategory: 'Grains',
    currentStock: 20,
    minimumStock: 5,
    maximumStock: 40,
    unit: 'kg',
    unitPrice: 80,
    supplier: 'Grain Suppliers',
    supplierContact: '+919876543304',
    location: 'Storage Room',
    description: 'Besan flour for pakoras and sweets',
    alertEnabled: true
  },
  {
    name: 'Cumin Seeds',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 5,
    minimumStock: 2,
    maximumStock: 15,
    unit: 'kg',
    unitPrice: 400,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Whole cumin seeds for tempering',
    alertEnabled: true
  },
  {
    name: 'Coriander Seeds',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 4,
    minimumStock: 1,
    maximumStock: 12,
    unit: 'kg',
    unitPrice: 350,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Whole coriander seeds for curry powder',
    alertEnabled: true
  },
  {
    name: 'Turmeric Powder',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 3,
    minimumStock: 1,
    maximumStock: 8,
    unit: 'kg',
    unitPrice: 200,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Pure turmeric powder for coloring and flavor',
    alertEnabled: true
  },
  {
    name: 'Red Chili Powder',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 6,
    unit: 'kg',
    unitPrice: 300,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Hot red chili powder for spiciness',
    alertEnabled: true
  },
  {
    name: 'Garam Masala',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 500,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Aromatic garam masala blend',
    alertEnabled: true
  },
  {
    name: 'Ginger',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 10,
    minimumStock: 3,
    maximumStock: 20,
    unit: 'kg',
    unitPrice: 80,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh ginger root',
    alertEnabled: true
  },
  {
    name: 'Garlic',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 8,
    minimumStock: 2,
    maximumStock: 15,
    unit: 'kg',
    unitPrice: 60,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh garlic bulbs',
    alertEnabled: true
  },
  {
    name: 'Green Chilies',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 3,
    minimumStock: 1,
    maximumStock: 8,
    unit: 'kg',
    unitPrice: 120,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh green chilies',
    alertEnabled: true
  },
  {
    name: 'Potatoes',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 30,
    minimumStock: 10,
    maximumStock: 60,
    unit: 'kg',
    unitPrice: 30,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh potatoes',
    alertEnabled: true
  },
  {
    name: 'Carrots',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 15,
    minimumStock: 5,
    maximumStock: 30,
    unit: 'kg',
    unitPrice: 40,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh carrots',
    alertEnabled: true
  },
  {
    name: 'Capsicum',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 8,
    minimumStock: 3,
    maximumStock: 15,
    unit: 'kg',
    unitPrice: 60,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh bell peppers',
    alertEnabled: true
  },
  {
    name: 'Cauliflower',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 6,
    minimumStock: 2,
    maximumStock: 12,
    unit: 'kg',
    unitPrice: 35,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh cauliflower',
    alertEnabled: true
  },
  {
    name: 'Cabbage',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 5,
    minimumStock: 2,
    maximumStock: 10,
    unit: 'kg',
    unitPrice: 25,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh cabbage',
    alertEnabled: true
  },
  {
    name: 'Spinach',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 4,
    minimumStock: 1,
    maximumStock: 8,
    unit: 'kg',
    unitPrice: 50,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh spinach leaves',
    alertEnabled: true
  },
  {
    name: 'Coriander Leaves',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 5,
    unit: 'kg',
    unitPrice: 80,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh coriander leaves',
    alertEnabled: true
  },
  {
    name: 'Mint Leaves',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 3,
    unit: 'kg',
    unitPrice: 100,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh mint leaves',
    alertEnabled: true
  },
  {
    name: 'Curry Leaves',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 120,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Cold Storage',
    description: 'Fresh curry leaves',
    alertEnabled: true
  },
  {
    name: 'Mutton',
    category: 'food_supplies',
    subcategory: 'Meat',
    currentStock: 8,
    minimumStock: 3,
    maximumStock: 15,
    unit: 'kg',
    unitPrice: 400,
    supplier: 'Fresh Meat Suppliers',
    supplierContact: '+919876543307',
    location: 'Cold Storage',
    description: 'Fresh mutton',
    alertEnabled: true
  },
  {
    name: 'Fish',
    category: 'food_supplies',
    subcategory: 'Meat',
    currentStock: 6,
    minimumStock: 2,
    maximumStock: 12,
    unit: 'kg',
    unitPrice: 300,
    supplier: 'Fresh Meat Suppliers',
    supplierContact: '+919876543307',
    location: 'Cold Storage',
    description: 'Fresh fish',
    alertEnabled: true
  },
  {
    name: 'Prawns',
    category: 'food_supplies',
    subcategory: 'Meat',
    currentStock: 4,
    minimumStock: 1,
    maximumStock: 8,
    unit: 'kg',
    unitPrice: 500,
    supplier: 'Fresh Meat Suppliers',
    supplierContact: '+919876543307',
    location: 'Cold Storage',
    description: 'Fresh prawns',
    alertEnabled: true
  },
  {
    name: 'Eggs',
    category: 'food_supplies',
    subcategory: 'Dairy',
    currentStock: 120,
    minimumStock: 30,
    maximumStock: 200,
    unit: 'pieces',
    unitPrice: 6,
    supplier: 'Dairy Products Ltd',
    supplierContact: '+919876543308',
    location: 'Cold Storage',
    description: 'Fresh eggs',
    alertEnabled: true
  },
  {
    name: 'Milk',
    category: 'food_supplies',
    subcategory: 'Dairy',
    currentStock: 20,
    minimumStock: 5,
    maximumStock: 40,
    unit: 'liters',
    unitPrice: 50,
    supplier: 'Dairy Products Ltd',
    supplierContact: '+919876543308',
    location: 'Cold Storage',
    description: 'Fresh milk',
    alertEnabled: true
  },
  {
    name: 'Yogurt',
    category: 'food_supplies',
    subcategory: 'Dairy',
    currentStock: 10,
    minimumStock: 3,
    maximumStock: 20,
    unit: 'kg',
    unitPrice: 80,
    supplier: 'Dairy Products Ltd',
    supplierContact: '+919876543308',
    location: 'Cold Storage',
    description: 'Fresh yogurt',
    alertEnabled: true
  },
  {
    name: 'Butter',
    category: 'food_supplies',
    subcategory: 'Dairy',
    currentStock: 5,
    minimumStock: 2,
    maximumStock: 10,
    unit: 'kg',
    unitPrice: 400,
    supplier: 'Dairy Products Ltd',
    supplierContact: '+919876543308',
    location: 'Cold Storage',
    description: 'Fresh butter',
    alertEnabled: true
  },
  {
    name: 'Ghee',
    category: 'food_supplies',
    subcategory: 'Dairy',
    currentStock: 3,
    minimumStock: 1,
    maximumStock: 6,
    unit: 'kg',
    unitPrice: 600,
    supplier: 'Dairy Products Ltd',
    supplierContact: '+919876543308',
    location: 'Cold Storage',
    description: 'Pure ghee',
    alertEnabled: true
  },
  {
    name: 'Cream',
    category: 'food_supplies',
    subcategory: 'Dairy',
    currentStock: 4,
    minimumStock: 1,
    maximumStock: 8,
    unit: 'kg',
    unitPrice: 120,
    supplier: 'Dairy Products Ltd',
    supplierContact: '+919876543308',
    location: 'Cold Storage',
    description: 'Fresh cream',
    alertEnabled: true
  },
  {
    name: 'Cheese',
    category: 'food_supplies',
    subcategory: 'Dairy',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 250,
    supplier: 'Dairy Products Ltd',
    supplierContact: '+919876543308',
    location: 'Cold Storage',
    description: 'Fresh cheese',
    alertEnabled: true
  },
  {
    name: 'Coconut',
    category: 'food_supplies',
    subcategory: 'Vegetables',
    currentStock: 15,
    minimumStock: 5,
    maximumStock: 30,
    unit: 'pieces',
    unitPrice: 25,
    supplier: 'Fresh Vegetables Co.',
    supplierContact: '+919876543306',
    location: 'Storage Room',
    description: 'Fresh coconuts',
    alertEnabled: true
  },
  {
    name: 'Coconut Oil',
    category: 'food_supplies',
    subcategory: 'Cooking Ingredients',
    currentStock: 8,
    minimumStock: 2,
    maximumStock: 15,
    unit: 'liters',
    unitPrice: 150,
    supplier: 'Oil Distributors',
    supplierContact: '+919876543305',
    location: 'Storage Room',
    description: 'Pure coconut oil',
    alertEnabled: true
  },
  {
    name: 'Mustard Oil',
    category: 'food_supplies',
    subcategory: 'Cooking Ingredients',
    currentStock: 6,
    minimumStock: 2,
    maximumStock: 12,
    unit: 'liters',
    unitPrice: 100,
    supplier: 'Oil Distributors',
    supplierContact: '+919876543305',
    location: 'Storage Room',
    description: 'Pure mustard oil',
    alertEnabled: true
  },
  {
    name: 'Sesame Oil',
    category: 'food_supplies',
    subcategory: 'Cooking Ingredients',
    currentStock: 3,
    minimumStock: 1,
    maximumStock: 6,
    unit: 'liters',
    unitPrice: 200,
    supplier: 'Oil Distributors',
    supplierContact: '+919876543305',
    location: 'Storage Room',
    description: 'Pure sesame oil',
    alertEnabled: true
  },
  {
    name: 'Ghee (Clarified Butter)',
    category: 'food_supplies',
    subcategory: 'Cooking Ingredients',
    currentStock: 4,
    minimumStock: 1,
    maximumStock: 8,
    unit: 'kg',
    unitPrice: 500,
    supplier: 'Oil Distributors',
    supplierContact: '+919876543305',
    location: 'Storage Room',
    description: 'Pure clarified butter',
    alertEnabled: true
  },
  {
    name: 'Sugar',
    category: 'food_supplies',
    subcategory: 'Sweeteners',
    currentStock: 25,
    minimumStock: 8,
    maximumStock: 50,
    unit: 'kg',
    unitPrice: 40,
    supplier: 'Sweetener Suppliers',
    supplierContact: '+919876543325',
    location: 'Storage Room',
    description: 'White sugar',
    alertEnabled: true
  },
  {
    name: 'Jaggery',
    category: 'food_supplies',
    subcategory: 'Sweeteners',
    currentStock: 10,
    minimumStock: 3,
    maximumStock: 20,
    unit: 'kg',
    unitPrice: 60,
    supplier: 'Sweetener Suppliers',
    supplierContact: '+919876543325',
    location: 'Storage Room',
    description: 'Pure jaggery',
    alertEnabled: true
  },
  {
    name: 'Honey',
    category: 'food_supplies',
    subcategory: 'Sweeteners',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 300,
    supplier: 'Sweetener Suppliers',
    supplierContact: '+919876543325',
    location: 'Storage Room',
    description: 'Pure honey',
    alertEnabled: true
  },
  {
    name: 'Salt',
    category: 'food_supplies',
    subcategory: 'Seasonings',
    currentStock: 15,
    minimumStock: 5,
    maximumStock: 30,
    unit: 'kg',
    unitPrice: 20,
    supplier: 'Seasoning Suppliers',
    supplierContact: '+919876543326',
    location: 'Storage Room',
    description: 'Iodized salt',
    alertEnabled: true
  },
  {
    name: 'Black Pepper',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 5,
    unit: 'kg',
    unitPrice: 800,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Whole black pepper',
    alertEnabled: true
  },
  {
    name: 'Cardamom',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 3,
    unit: 'kg',
    unitPrice: 1200,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Green cardamom pods',
    alertEnabled: true
  },
  {
    name: 'Cinnamon',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 3,
    unit: 'kg',
    unitPrice: 600,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Cinnamon sticks',
    alertEnabled: true
  },
  {
    name: 'Cloves',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 1000,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Whole cloves',
    alertEnabled: true
  },
  {
    name: 'Bay Leaves',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 400,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Dried bay leaves',
    alertEnabled: true
  },
  {
    name: 'Fenugreek Seeds',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 3,
    unit: 'kg',
    unitPrice: 200,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Whole fenugreek seeds',
    alertEnabled: true
  },
  {
    name: 'Mustard Seeds',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 150,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Whole mustard seeds',
    alertEnabled: true
  },
  {
    name: 'Fennel Seeds',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 3,
    unit: 'kg',
    unitPrice: 300,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Whole fennel seeds',
    alertEnabled: true
  },
  {
    name: 'Star Anise',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 800,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Whole star anise',
    alertEnabled: true
  },
  {
    name: 'Nutmeg',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 1500,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Whole nutmeg',
    alertEnabled: true
  },
  {
    name: 'Mace',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 2000,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Mace blades',
    alertEnabled: true
  },
  {
    name: 'Saffron',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'grams',
    unitPrice: 500,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Pure saffron threads',
    alertEnabled: true
  },
  {
    name: 'Tamarind',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 3,
    minimumStock: 1,
    maximumStock: 6,
    unit: 'kg',
    unitPrice: 100,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Dried tamarind',
    alertEnabled: true
  },
  {
    name: 'Dry Red Chilies',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 200,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Dried red chilies',
    alertEnabled: true
  },
  {
    name: 'Coriander Powder',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 180,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Ground coriander powder',
    alertEnabled: true
  },
  {
    name: 'Cumin Powder',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 250,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Ground cumin powder',
    alertEnabled: true
  },
  {
    name: 'Fenugreek Powder',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 3,
    unit: 'kg',
    unitPrice: 150,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Ground fenugreek powder',
    alertEnabled: true
  },
  {
    name: 'Asafoetida',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 800,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Asafoetida powder',
    alertEnabled: true
  },
  {
    name: 'Dry Mango Powder',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 3,
    unit: 'kg',
    unitPrice: 120,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Amchur powder',
    alertEnabled: true
  },
  {
    name: 'Kasuri Methi',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 300,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Dried fenugreek leaves',
    alertEnabled: true
  },
  {
    name: 'Dried Coconut',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 80,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Dried coconut flakes',
    alertEnabled: true
  },
  {
    name: 'Poppy Seeds',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 400,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'White poppy seeds',
    alertEnabled: true
  },
  {
    name: 'Sesame Seeds',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 200,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'White sesame seeds',
    alertEnabled: true
  },
  {
    name: 'Pumpkin Seeds',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 300,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Dried pumpkin seeds',
    alertEnabled: true
  },
  {
    name: 'Sunflower Seeds',
    category: 'food_supplies',
    subcategory: 'Spices',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 150,
    supplier: 'Spice Traders',
    supplierContact: '+919876543320',
    location: 'Spice Rack',
    description: 'Dried sunflower seeds',
    alertEnabled: true
  },
  {
    name: 'Almonds',
    category: 'food_supplies',
    subcategory: 'Nuts',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 600,
    supplier: 'Nut Suppliers',
    supplierContact: '+919876543330',
    location: 'Storage Room',
    description: 'Whole almonds',
    alertEnabled: true
  },
  {
    name: 'Cashews',
    category: 'food_supplies',
    subcategory: 'Nuts',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 500,
    supplier: 'Nut Suppliers',
    supplierContact: '+919876543330',
    location: 'Storage Room',
    description: 'Whole cashews',
    alertEnabled: true
  },
  {
    name: 'Pistachios',
    category: 'food_supplies',
    subcategory: 'Nuts',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 800,
    supplier: 'Nut Suppliers',
    supplierContact: '+919876543330',
    location: 'Storage Room',
    description: 'Shelled pistachios',
    alertEnabled: true
  },
  {
    name: 'Walnuts',
    category: 'food_supplies',
    subcategory: 'Nuts',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 700,
    supplier: 'Nut Suppliers',
    supplierContact: '+919876543330',
    location: 'Storage Room',
    description: 'Shelled walnuts',
    alertEnabled: true
  },
  {
    name: 'Raisins',
    category: 'food_supplies',
    subcategory: 'Nuts',
    currentStock: 2,
    minimumStock: 1,
    maximumStock: 4,
    unit: 'kg',
    unitPrice: 200,
    supplier: 'Nut Suppliers',
    supplierContact: '+919876543330',
    location: 'Storage Room',
    description: 'Dried raisins',
    alertEnabled: true
  },
  {
    name: 'Dates',
    category: 'food_supplies',
    subcategory: 'Nuts',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 300,
    supplier: 'Nut Suppliers',
    supplierContact: '+919876543330',
    location: 'Storage Room',
    description: 'Dried dates',
    alertEnabled: true
  },
  {
    name: 'Figs',
    category: 'food_supplies',
    subcategory: 'Nuts',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 400,
    supplier: 'Nut Suppliers',
    supplierContact: '+919876543330',
    location: 'Storage Room',
    description: 'Dried figs',
    alertEnabled: true
  },
  {
    name: 'Apricots',
    category: 'food_supplies',
    subcategory: 'Nuts',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 350,
    supplier: 'Nut Suppliers',
    supplierContact: '+919876543330',
    location: 'Storage Room',
    description: 'Dried apricots',
    alertEnabled: true
  },
  {
    name: 'Prunes',
    category: 'food_supplies',
    subcategory: 'Nuts',
    currentStock: 1,
    minimumStock: 1,
    maximumStock: 2,
    unit: 'kg',
    unitPrice: 250,
    supplier: 'Nut Suppliers',
    supplierContact: '+919876543330',
    location: 'Storage Room',
    description: 'Dried prunes',
    alertEnabled: true
  }
];

async function seedAdditionalInventory() {
  try {
    console.log('Seeding additional inventory data...');
    
    for (const item of additionalInventoryData) {
      await Inventory.create(item);
    }
    
    console.log(`✅ Seeded ${additionalInventoryData.length} additional inventory items successfully!`);
  } catch (error) {
    console.error('❌ Error seeding additional inventory:', error);
  }
}

module.exports = { seedAdditionalInventory };
